/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class brownshome_apss_UnderlyingModels */

#ifndef _Included_brownshome_apss_UnderlyingModels
#define _Included_brownshome_apss_UnderlyingModels
#ifdef __cplusplus
extern "C" {
#endif
#undef brownshome_apss_UnderlyingModels_rE
#define brownshome_apss_UnderlyingModels_rE 6731000.0
#undef brownshome_apss_UnderlyingModels__003bcE
#define brownshome_apss_UnderlyingModels__003bcE 3.986004418E14
/*
 * Class:     brownshome_apss_UnderlyingModels
 * Method:    getWMMData
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_brownshome_apss_UnderlyingModels_getWMMData
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
